---
include:
  - board: ergohaven
    shield: velvet_v3_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_qube-ergohaven-zmk

  - board: ergohaven
    shield: velvet_v3_left_qube

  - board: ergohaven
    shield: settings_reset
